# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:18

options:
  docker: true
  size: 2x

pipelines:
  default:
    - parallel:
        steps:
          - step:
              name: Build App Root
              caches:
                - node
              script: # Modify the commands below to build your repository.
                - npm install
          - step:
              name: Build In-Page Editor
              script:
                - cd static/in-page-editor
                - npm install --legacy-peer-deps
                - npm run build
          - step:
              name: Build Bitbucket Snippet
              script:
                - cd static/bitbucket-snippet
                - npm install --legacy-peer-deps
                - npm run build
          - step:
              name: Build Gist Code Macro
              script:
                - cd static/gist-code-macro
                - npm install --legacy-peer-deps
                - npm run build
          - step:
              name: Build Paste Code Macro
              script:
                - cd static/paste-code-macro
                - npm install --legacy-peer-deps
                - npm run build
          - step:
              name: Build docker image
              script:
                # Used for accessing packages.atlassian.com
                - pipe: docker://atlassian/artifactory-sidekick:latest
                - source .artifactory/activate.sh
                # build base image (node@alpine + python dependencies + hugo)
                - cd remotes/connect
                - docker build --tag="cloud-code-macro-test:${BITBUCKET_BUILD_NUMBER}" .
                # don't push it, this is just to test the build
              services:
                - docker
              caches:
                - docker
          - step:
              name: Test Service Descriptor Generation
              script:
                # generate the service descriptor
                - cd remotes/connect
                - echo "RELEASE_VERSION" > "template-vars.csv"
                - echo "${BITBUCKET_BUILD_NUMBER}" >> "template-vars.csv"
                - npm install mustang
                - npm run pipeline:mustang
              services:
                - docker
              caches:
                - docker
  branches:
    master:
      - step:
          name: Build docker image
          script:
            # Used for accessing packages.atlassian.com
            - pipe: docker://atlassian/artifactory-sidekick:latest
              variables:
                COMPLIANT: "true"
            - source .artifactory/activate.sh
            # set up step variables and auth data
            - export DOCKER_URL="docker.atl-paas.net"
            # build base image (node@alpine + python dependencies + hugo)
            - cd remotes/connect
            - docker build --tag="${DOCKER_URL}/sox/atlassian/cloud-code-macro:${BITBUCKET_BUILD_NUMBER}" .
            - docker push "${DOCKER_URL}/sox/atlassian/cloud-code-macro:${BITBUCKET_BUILD_NUMBER}"
          services:
            - docker
          caches:
            - docker
      - step:
          name: Deploy to staging
          deployment: staging
          script:
            # set up step variables and auth data
            - export MICROS_TOKEN="$MICROS_TOKEN:$PIPELINES_JWT_TOKEN"
            - export MICROS_URL="wss://micros-proxy.services.atlassian.com"
            # Download and extract Atlas CLI
            - cd remotes/connect
            - curl -fL https://statlas.prod.atl-paas.net/atlas-cli/linux/atlas-latest-linux-amd64.tar.gz | tar -xzp atlas
            # Install the Micros plugin
            - ./atlas plugin install -n micros
            # generate the service descriptor
            - echo "RELEASE_VERSION" > "template-vars.csv"
            - echo "${BITBUCKET_BUILD_NUMBER}" >> "template-vars.csv"
            - npm install mustang
            - npm run pipeline:mustang
            # micros deploy the service
            - ./atlas micros service deploy -s cloud-code-macro -f service-descriptor.json -e adev
          services:
            - docker
          caches:
            - docker
      - step:
          name: Deploy to prod
          deployment: production
          trigger: manual
          script:
            # set up step variables and auth data
            - export MICROS_TOKEN="$MICROS_TOKEN:$PIPELINES_JWT_TOKEN"
            - export MICROS_URL="wss://micros-proxy.services.atlassian.com"
            # Download and extract Atlas CLI
            - cd remotes/connect
            - curl -fL https://statlas.prod.atl-paas.net/atlas-cli/linux/atlas-latest-linux-amd64.tar.gz | tar -xzp atlas
            # Install the Micros plugin
            - ./atlas plugin install -n micros
            # generate the service descriptor
            - echo "RELEASE_VERSION" > "template-vars.csv"
            - echo "${BITBUCKET_BUILD_NUMBER}" >> "template-vars.csv"
            - npm install mustang
            - npm run pipeline:mustang
            # micros deploy the service
            - ./atlas micros service deploy -s cloud-code-macro -f service-descriptor.json -e prod-east
          services:
            - docker
          caches:
            - docker
