# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:22

options:
  docker: true
  size: 2x

pipelines:
  default:
    - parallel:
        steps:
          - step:
              name: Build App Root
              caches:
                - node
              script: # Modify the commands below to build your repository.
                - npm install
          - step:
              name: Build In-Page Editor
              script:
                - pipe: docker://atlassian/artifactory-sidekick:latest
                - source .artifactory/activate.sh
                - cd static/in-page-editor
                - npm install --legacy-peer-deps
                - npm run build
          - step:
              name: Build Bitbucket Snippet
              script:
                - pipe: docker://atlassian/artifactory-sidekick:latest
                - source .artifactory/activate.sh
                - cd static/bitbucket-snippet
                - npm install --legacy-peer-deps
                - npm run build
          - step:
              name: Build Gist Code Macro
              script:
                - pipe: docker://atlassian/artifactory-sidekick:latest
                - source .artifactory/activate.sh
                - cd static/gist-code-macro
                - npm install --legacy-peer-deps
                - npm run build
          - step:
              name: Build Paste Code Macro
              script:
                - pipe: docker://atlassian/artifactory-sidekick:latest
                - source .artifactory/activate.sh
                - cd static/paste-code-macro
                - npm install --legacy-peer-deps
                - npm run build
